name: test-all

on:
    workflow_dispatch:
    pull_request:

jobs:
  prepare_package_for_release:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js 18
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --non-interactive
      - name: "Set new react-native version and commit changes"
        run: |
          LATEST=false
          DRYRUN=true
          VERSION=$(grep '"version"' package.json | cut -d '"' -f 4 | head -1)
          echo "Using the version from the package.json: $VERSION"
          node ./scripts/prepare-package-for-release.js -v "$VERSION" -l $LATEST --dry-run $DRYRUN
  prepare_hermes_workspace:
    runs-on: ubuntu-latest
    env:
      HERMES_WS_DIR: /tmp/hermes
      HERMES_VERSION_FILE: packages/react-native/sdks/.hermesversion
      BUILD_FROM_SOURCE: true
    outputs:
      react-native-version: ${{ steps.react-native-version.outputs.version }}
      hermes-version: ${{ steps.hermes-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Use Node.js 18
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18
          cache: 'yarn'
      - name: Cache hermes workspace
        uses: actions/cache@v4.0.0
        with:
          path: /tmp/hermes
          key: hermes
      - name: Setup hermes version
        id: hermes-version
        run: |
          mkdir -p "/tmp/hermes" "/tmp/hermes/download" "/tmp/hermes/hermes"

          if [ -f "$HERMES_VERSION_FILE" ]; then
            echo "Hermes Version file found! Using this version for the build:"
            echo "VERSION=$(cat $HERMES_VERSION_FILE)" >> "$GITHUB_OUTPUT"
          else
            echo "Hermes Version file not found!!!"
            echo "Using the last commit from main for the build:"
            HERMES_TAG_SHA=$(git ls-remote https://github.com/$GITHUB_REPOSITORY main | cut -f 1 | tr -d '[:space:]')
            echo "VERSION=$HERMES_TAG_SHA" >> "$GITHUB_OUTPUT"
          fi
          echo "Hermes commit is $HERMES_TAG_SHA"
      - name: Get react-native version
        id: react-native-version
        run: |
          VERSION=$(cat packages/react-native/package.json | jq -r '.version')
          # Save the react native version we are building in an output variable so we can use that file as part of the cache key.
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
          echo "React Native Version is $VERSION"
      - name: Cache hermes workspace
        uses: actions/cache@v4.0.0
        with:
          path: |
            /tmp/hermes/download/
            /tmp/hermes/hermes/
          key: v5-hermes-${{ github.job }}-${{ steps.hermes-version.outputs.version }}
      - name: Yarn- Install Dependencies
        if: ${{ contains(github.event.head_commit.message, 'Bump metro@') }}
        run: yarn install --non-interactive
      - name: Download Hermes tarball
        run: |
          node packages/react-native/scripts/hermes/prepare-hermes-for-build ${{ github.event.pull_request.html_url }}
          cp packages/react-native/sdks/download/* $HERMES_WS_DIR/download/.
          cp -r packages/react-native/sdks/hermes/* $HERMES_WS_DIR/hermes/.

          echo ${{ steps.hermes-version.outputs.version }}
      
  build_hermesc_apple:
    runs-on: macos-12
    needs: prepare_hermes_workspace
    env:
      HERMES_WS_DIR: /tmp/hermes
      HERMES_TARBALL_ARTIFACTS_DIR: /tmp/hermes/hermes-runtime-darwin
    steps:
      - name: Cache hermes workspace
        uses: actions/cache@v4.0.0
        with:
          path: /tmp/hermes
          key: hermes
      - name: Restore git cache
        uses: actions/cache/restore@v4.0.0
        with:
          path: .git
          key: v1-checkout-checkout-${{ runner.arch }}-${{ github.ref }}-${{ github.sha }}
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Save git cache
        uses: actions/cache/save@v4.0.0
        with:
          path: .git
          key: v1-checkout-checkout-${{ runner.arch }}-${{ github.ref }}-${{ github.sha }}

      ## This above step needs to be put into it's own action, and it needs to set an output for the value of the react native version.  
      - name: Setup Hermes workspace
        run: |
          mkdir -p $HERMES_OSXBIN_ARTIFACTS_DIR ./packages/react-native/sdks/hermes
          cp -r $HERMES_WS_DIR/hermes/* ./packages/react-native/sdks/hermes/.
          cp -r ./packages/react-native/sdks/hermes-engine/utils ./packages/react-native/sdks/hermes/.

      - name: Hermes apple cache
        uses: actions/cache@v4.0.0
        with:
          path: ./packages/react-native/sdks/hermes/build_host_hermesc
          key: v2-hermesc-apple-${{ needs.prepare_hermes_workspace.outputs.hermes-version }}-${{ needs.prepare_hermes_workspace.outputs.react-native-version }}
      - name: "Build HermesC Apple"
        run: |
          cd ./packages/react-native/sdks/hermes || exit 1
          . ./utils/build-apple-framework.sh
          build_host_hermesc_if_needed
